pyJasper - a set of python based tools to handle JasperReports.
Since jasper reports is a Java application you need Java installed.
Jython (bundled with pyJasper) is used to access  the JasperReports library.

See https://cybernetics.hudora.biz/projects/wiki/pyJasper for further details.

Files:

client.py                      - contains high-level Python functions for report generation. Should 
                                 theoretically be able to work with report generators other than
                                 JasperReports. So far builds on JasperClient.py.
backend/                       - contains tools to drive JasperReports and actually build reports 
                                 The backend was once based on XmlJasperInterface 
                                 by Jonas Schwertfeger but hase benn moving away from
                                 it for some time.
backend/XmlJasperInterface.py  - driving jasper reports to generate PDFs. Also a command line application
                                 to generate reports.
backend/XmlJasperInterface.sh  - shell script to start XmlJasperInterface.py
backend/lib                    - JasperReports and Jython Java Libraries
reports                        - report source files (*.jrxml)
sample-xml                     - sample XML files to work with reports
sample-pdf                     - sample PDFs generated by using reports with sample XML
