#!/sbin/sh
# Start/stop client SAS MetaData service
#
.. /lib/svc/share/smf_include.sh



case "$1" in
'start')
        cd /opt/jasper/pyjasper/backend/
        /opt/jasper/pyjasper/backend/pyJasper-httpd.sh &
        sleep 2
        ;;
'stop')
        #kill the jasper service
        ;;
*)
        echo "Usage: $0 { start | stop }"
        exit 1
        ;;
esac
exit $SMF_EXIT_OK

